version: "3"

services:
  alice:
    build:
      alice
    image: alice:0.1
    container_name: alice
    ports:
    - "8080:8080"

  bob:
    build:
      bob
    image: bob:0.1
    container_name: bob
    ports:
    - "8081:8081"